### ISSUE TITLE
coq-io-system → coq-list-string >= 2.0.0 no matching version

### ISSUE THREAD

**Issue by imel96** [coq-io/system#3]
Hi,

I tried installing coq-io-system using opam. It failed because it requires coq-list-string >= 2.0.0 but opam says only version 1.0.0 is available.

I'm using opam version 2.0.2

Thanks

**Comment by clarus** [comment]
Hi,

OK did not maintain this package for some time, and apparently some packages were removed with the update to OPAM 2. I am looking into it.

**Comment by clarus** [comment]
I opened this pull-request to fix the issue: https://github.com/coq/opam-coq-archive/pull/650 However, there are other missing dependencies preventing to install this package.

**Comment by imel96** [comment]
Thanks for updating that. I tried compiling OPAM 1.2.2 & 1.3.0 but failed, maybe they don't work with my OCaml (v4.07.1).
If you have any pointers on how to try coq.io, that'd be great!
